name: character_list
description: Home feature
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  navigation:
    path: ../../navigation
    
  flutter_bloc: ^8.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8